name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api Docker Image
        id: api_deploy
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ghcr.io/${{github.repository}}/api:${{github.sha}}

      - name: Build and push web Docker Image
        id: web_deploy
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ghcr.io/${{github.repository}}/web:${{github.sha}}
          build-args: |
            NEXT_PUBLIC_API_PATH=${{SECRETS.NEXT_PUBLIC_API_PATH}}
            SENTRY_AUTH_TOKEN=${{SECRETS.SENTRY_AUTH_TOKEN}}
            NEXT_PUBLIC_TEST=${{SECRETS.NEXT_PUBLIC_TEST}}

      # - name: Push api to dokku
      #   uses: dokku/github-action@master
      #   with:
      #     git_remote_url: ssh://dokku@143.198.146.197:22/api
      #     ssh_private_key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"

      # - name: Push web to dokku
      #   uses: dokku/github-action@master
      #   with:
      #     git_remote_url: "ssh://143.198.146.197:22/appname"
      #     ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
      #     git_push_flags: "--force"
      #     ci_commit: ${{ steps.web_deploy.outputs.commit_sha }}

      # Couldn't get this to authenticate
      - name: Trigger dokku deployment
        uses: appleboy/ssh-action@master
        with:
          host: 143.198.146.197
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          debug: true
          script: |
            dokku git:from-image api ghcr.io/${{github.repository}}/api:${{github.sha}}
            dokku git:from-image web ghcr.io/${{github.repository}}/web:${{github.sha}}

      - name: Delete old api images
        uses: actions/delete-package-versions@v2
        with:
          owner: "doggo-sports"
          repo: "services"
          package-name: "api"
          token: ${{secrets.GITHUB_TOKEN}}
          min-versions-to-keep: 3

      - name: Delete old web images
        uses: actions/delete-package-versions@v2
        with:
          owner: "doggo-sports"
          repo: "services"
          package-name: "web"
          token: ${{secrets.GITHUB_TOKEN}}
          min-versions-to-keep: 3
